//
//  CreateNewAccountInteractor.swift
//  Tile
//
//  Created by  Tim on 16.11.2017.
//  Copyright (c) 2017 TimHazhyi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateNewAccountBusinessLogic
{
  func doSomething(request: CreateNewAccount.Something.Request)
}

protocol CreateNewAccountDataStore
{
  //var name: String { get set }
}

class CreateNewAccountInteractor: CreateNewAccountBusinessLogic, CreateNewAccountDataStore
{
  var presenter: CreateNewAccountPresentationLogic?
  var worker: CreateNewAccountWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CreateNewAccount.Something.Request)
  {
    worker = CreateNewAccountWorker()
    worker?.doSomeWork()
    
    let response = CreateNewAccount.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
