//
//  CreateNewAccountPresenter.swift
//  Tile
//
//  Created by  Tim on 16.11.2017.
//  Copyright (c) 2017 TimHazhyi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateNewAccountPresentationLogic
{
  func presentSomething(response: CreateNewAccount.Something.Response)
}

class CreateNewAccountPresenter: CreateNewAccountPresentationLogic
{
  weak var viewController: CreateNewAccountDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CreateNewAccount.Something.Response)
  {
    let viewModel = CreateNewAccount.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
