//
//  TilesModels.swift
//  Tile
//
//  Created by  Tim on 16.10.2017.
//  Copyright (c) 2017 TimHazhyi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Tiles
{
    enum ConnectionStatus
    {
        struct Request
        {
        }
        struct Response
        {
            var status: Bool
        }
        struct ViewModel
        {
            var alert: UIAlertController
        }
    }
    enum NewTile
    {
        struct Request
        {
            var id: String
            var name: String
            var userId: String
        }
        struct Response
        {
            var status: String
            var tile: Tile
        }
        struct ViewModel
        {
            var tile: Tile
        }
    }
    enum GetTiles
    {
        struct Request
        {
            var userId: String
        }
        struct Response
        {
            var tiles: [Tile]
        }
        struct ViewModel
        {
            var tiles: [Tile]
        }
    }
    
}
