//
//  TilesPresenter.swift
//  Tile
//
//  Created by  Tim on 16.10.2017.
//  Copyright (c) 2017 TimHazhyi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TilesPresentationLogic
{
    func presentSelectedImage(response: Tiles.SelectedImage.Response)
}

class TilesPresenter: TilesPresentationLogic
{
    weak var viewController: TilesDisplayLogic?
    
    // MARK: Do something
    
    func presentSelectedImage(response: Tiles.SelectedImage.Response) {
        let viewModel = Tiles.SelectedImage.ViewModel(image: response.image)
        viewController?.displaySelectedImage(viewModel: viewModel)
    }
    
}
