//
//  EditImagePresenter.swift
//  Tile
//
//  Created by  Tim on 16.10.2017.
//  Copyright (c) 2017 TimHazhyi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditImagePresentationLogic
{
    func presentFiltersScrollView(response: EditImage.Filters.Response)
    func setImage(image: UIImage)
}

class EditImagePresenter: EditImagePresentationLogic
{
    weak var viewController: EditImageDisplayLogic?
    
    // MARK: Do something
    
    func presentFiltersScrollView(response: EditImage.Filters.Response) {
        let scrollView = UIScrollView()
        var xCoord: CGFloat = 5
        let yCoord: CGFloat = 5
        let buttonWidth:CGFloat = 70
        let buttonHeight: CGFloat = 70
        let gapBetweenButtons: CGFloat = 5
        var itemCount = 0
        
        for (index, i) in response.images.enumerated() {
            itemCount = index
            let filterButton = UIButton(type: .custom)
            filterButton.frame = CGRect(x: xCoord, y: yCoord, width: buttonWidth, height: buttonHeight)
            filterButton.tag = itemCount
            filterButton.addTarget(self, action: #selector(filterButtonTapped(sender:)), for: .touchUpInside)
            filterButton.layer.cornerRadius = 6
            filterButton.clipsToBounds = true
            let imageForButton = UIImage(cgImage: i)
            filterButton.setBackgroundImage(imageForButton, for: .normal)
            filterButton.contentMode = .scaleAspectFit
            xCoord +=  buttonWidth + gapBetweenButtons
            scrollView.addSubview(filterButton)
        }
        
        scrollView.contentSize = CGSize(width: buttonWidth * CGFloat(itemCount + 2), height: yCoord)
        
        let viewModel = scrollView
        viewController?.displayFiltersScrollView(viewModel: viewModel)
    }
    
    @objc func filterButtonTapped(sender: UIButton) {
        viewController?.filterButtonTapped(sender: sender)
    }
    
    func setImage(image: UIImage) {
        viewController?.setImage(image: image)
    }
}
