//
//  EditImageRouter.swift
//  Tile
//
//  Created by  Tim on 16.10.2017.
//  Copyright (c) 2017 TimHazhyi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol EditImageRoutingLogic
{
    func routeToTiles(segue: UIStoryboardSegue?)
}

protocol EditImageDataPassing
{
    var dataStore: EditImageDataStore? { get }
}

class EditImageRouter: NSObject, EditImageRoutingLogic, EditImageDataPassing
{
    weak var viewController: EditImageViewController?
    var dataStore: EditImageDataStore?
    
    // MARK: Routing
    
    func routeToTiles(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! TilesViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToTiles(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "TilesViewController") as! TilesViewController
            var destinationDS = destinationVC.router!.dataStore!
//            passDataToTiles(source: dataStore!, destination: &destinationDS)
            navigateToTiles(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToTiles(source: EditImageViewController, destination: TilesViewController)
    {
        source.dismiss(animated: true, completion: nil)
    }
    
    // MARK: Passing data
    
    func passDataToTiles(source: EditImageDataStore, destination: inout TilesDataStore)
    {
//        destination.selectedImage = source.imageWithFilter
    }
}
