//
//  EditImageInteractor.swift
//  Tile
//
//  Created by  Tim on 16.10.2017.
//  Copyright (c) 2017 TimHazhyi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditImageBusinessLogic
{
    func applyFilters(request: EditImage.Filters.Request)
    func saveImageForTile(request: EditImage.ImageForTile.Request)
    
    func setImage()
    func setImageWithFilter(image: UIImage)
}

protocol EditImageDataStore
{
    var tile: Tile? {get set}
    var imageWithFilter: UIImage? {get set}
}

class EditImageInteractor: EditImageBusinessLogic, EditImageDataStore
{
    var tile: Tile?
    var imageWithFilter: UIImage?
    var presenter: EditImagePresentationLogic?
    var worker: EditImageWorker?
    
    // MARK: Do something
    
    func applyFilters(request: EditImage.Filters.Request) {
        worker = EditImageWorker()
        DispatchQueue.global().async {
            let images = self.worker?.applyGPUImageFilters(originalImage: request.originalImage)
//            let images = self.worker?.applyFilters(originalImage: request.originalImage, filtrerNames: request.filters)
            DispatchQueue.main.async {
                let response = EditImage.Filters.Response(images: images!)
                self.presenter?.presentFiltersScrollView(response: response)
            }
        }
    }
    
    func saveImageForTile(request: EditImage.ImageForTile.Request) {
        FirebaseService.shared.upload(image: request.image, forTile: tile!.id) { url in
            let response = EditImage.ImageForTile.Response(url: url)
            self.presenter?.presentTileWithImage(responce: response)
        }
    }
    
    func setImage() {
//        presenter?.setImage(image: originalImage!)
    }
    
    func setImageWithFilter(image: UIImage) {
        self.imageWithFilter = image
    }
}
