//
//  EditImageModels.swift
//  Tile
//
//  Created by  Tim on 16.10.2017.
//  Copyright (c) 2017 TimHazhyi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum EditImage
{
    // MARK: Use cases
    enum Filters {
        struct Request
        {
            var filters: [String]
            var originalImage: UIImage
        }
        struct Response
        {
            var images: [CGImage]
        }
        struct ViewModel
        {
            var filtersScrollView: UIScrollView
        }
    }
}
