//
//  EditImageInteractor.swift
//  Tile
//
//  Created by  Tim on 16.10.2017.
//  Copyright (c) 2017 TimHazhyi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditImageBusinessLogic
{
    func doSomething(request: EditImage.Something.Request)
    func applyFilters(request: EditImage.Filters.Request)
    func setImage()
    func setImageWithFilter(image: UIImage)
}

protocol EditImageDataStore
{
    var originalImage: UIImage? {get set}
    var imageWithFilter: UIImage? {get set}
    //var name: String { get set }
}

class EditImageInteractor: EditImageBusinessLogic, EditImageDataStore
{
    var originalImage: UIImage?
    var imageWithFilter: UIImage?
    var presenter: EditImagePresentationLogic?
    var worker: EditImageWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: EditImage.Something.Request)
    {
        worker = EditImageWorker()
        worker?.doSomeWork()
        
        let response = EditImage.Something.Response()
        presenter?.presentSomething(response: response)
    }
    
    func applyFilters(request: EditImage.Filters.Request) {
        worker = EditImageWorker()
        DispatchQueue.global().async {
            let images = self.worker?.applyFilters(originalImage: request.originalImage, filtrerNames: request.filters)
            DispatchQueue.main.async {
                let response = EditImage.Filters.Response(images: images!)
                self.presenter?.presentFiltersScrollView(response: response)
            }
        }
    }
    
    func setImage() {
        presenter?.setImage(image: originalImage!)
    }
    
    func setImageWithFilter(image: UIImage) {
        self.imageWithFilter = image
    }
}
