//
//  EditImageWorker.swift
//  Tile
//
//  Created by  Tim on 16.10.2017.
//  Copyright (c) 2017 TimHazhyi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class EditImageWorker
{

    func doSomeWork()
    {
    }
    
    func applyFilters(originalImage: UIImage, filtrerNames: [String]) -> [CGImage] {
        var filteredImages: [CGImage] = []
        let ciContext = CIContext(options: nil)
        let coreImage = CIImage(image: originalImage)
        for i in filtrerNames {
            let filter = CIFilter(name: i)
            filter!.setDefaults()
            filter!.setValue(coreImage, forKey: kCIInputImageKey)
            let filteredImageData = filter!.value(forKey: kCIOutputImageKey) as! CIImage
            let filteredImageRef = ciContext.createCGImage(filteredImageData, from: filteredImageData.extent)
            filteredImages.append(filteredImageRef!)
        }
        return filteredImages
    }
}
