//
//  LoginWorker.swift
//  Tile
//
//  Created by  Tim on 12.10.2017.
//  Copyright (c) 2017 TimHazhyi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker
{
    func doSomeWork()
    {
    }
    func facebookSignIn() {
        SignIn.shared.facebookSignIn()
    }
    func googleSignIn() {
        SignIn.shared.googleSignIn()
    }
    func emailSignIn(email: String, pass: String) {
        SignIn.shared.emailSignIn(email: email, pass: pass)
    }
}
