//
//  LoginInteractor.swift
//  Tile
//
//  Created by  Tim on 12.10.2017.
//  Copyright (c) 2017 TimHazhyi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
    func doSomething(request: Login.Something.Request)
    func facebookSignIn()
    func googleSignIn()
    func emailSignIn(email: String, pass: String)
}

protocol LoginDataStore
{
    //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Login.Something.Request)
    {
        worker = LoginWorker()
        worker?.doSomeWork()
        
        let response = Login.Something.Response()
        presenter?.presentSomething(response: response)
    }
    
    func facebookSignIn() {
        worker = LoginWorker()
        worker?.facebookSignIn()
    }
    
    func googleSignIn() {
        worker = LoginWorker()
        worker?.googleSignIn()
    }
    
    func emailSignIn(email: String, pass: String) {
        worker = LoginWorker()
        worker?.emailSignIn(email: email, pass: pass)
    }
}
